name: Continuous Deployment (Prod)

on:
    push:
        branches: ["main"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Docker login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_SECRET }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push school image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: rawadhossain/todo-app:${{ github.sha }}

            # - name: Clone staging-ops repo, update image tags, and push tags
            #   env:
            #       PAT: ${{ secrets.PAT }}
            #   run: |
            #       git clone https://github.com/100xdevs-cohort-3/argo-deployment.git
            #       cd argo-deployment

            #       sed -i 's|image: 100xdevs/todo-app-week-39:.*|image: 100xdevs/todo-app-week-39:${{ github.sha }}|' manifest.yml

            #       git config user.name "GitHub Actions Bot"
            #       git config user.email "actions@github.com"
            #       git add .
            #       git commit -m "Update school server image tags to ${{ github.sha }}"
            #       git push https://${PAT}@github.com/100xdevs-cohort-3/argo-deployment.git main
